-- Backfill ISO 3166-1 alpha-2 codes for countries that have none.
-- flag-icons (and the public country statistics / editorial flags) rely on the
-- two-letter code; emoji flags were used before but do not render on many
-- servers/browsers. Only rows with an empty code are touched, so this is safe
-- to re-run.
UPDATE fix_country AS f
SET country_code = v.iso
FROM (VALUES
    ('Andorra', 'ad'),
    ('Angola', 'ao'),
    ('Bahamas', 'bs'),
    ('Bahrain', 'bh'),
    ('Barbados', 'bb'),
    ('Belize', 'bz'),
    ('Benin', 'bj'),
    ('Bhutan', 'bt'),
    ('Bolivia', 'bo'),
    ('Botswana', 'bw'),
    ('Brunei', 'bn'),
    ('Burkina Faso', 'bf'),
    ('Burundi', 'bi'),
    ('Cameroon', 'cm'),
    ('Cape Verde', 'cv'),
    ('Central African Republic', 'cf'),
    ('Chad', 'td'),
    ('Comoros', 'km'),
    ('Congo', 'cg'),
    ('Costa Rica', 'cr'),
    ('Cuba', 'cu'),
    ('Cyprus', 'cy'),
    ('Djibouti', 'dj'),
    ('Dominica', 'dm'),
    ('Dominican Republic', 'do'),
    ('East Timor', 'tl'),
    ('Ecuador', 'ec'),
    ('El Salvador', 'sv'),
    ('Equatorial Guinea', 'gq'),
    ('Eritrea', 'er'),
    ('Eswatini', 'sz'),
    ('Fiji', 'fj'),
    ('Gabon', 'ga'),
    ('Gambia', 'gm'),
    ('Grenada', 'gd'),
    ('Guatemala', 'gt'),
    ('Guinea', 'gn'),
    ('Guinea-Bissau', 'gw'),
    ('Guyana', 'gy'),
    ('Haiti', 'ht'),
    ('Honduras', 'hn'),
    ('Iceland', 'is'),
    ('Jamaica', 'jm'),
    ('Kiribati', 'ki'),
    ('Laos', 'la'),
    ('Lesotho', 'ls'),
    ('Liberia', 'lr'),
    ('Liechtenstein', 'li'),
    ('Luxembourg', 'lu'),
    ('Madagascar', 'mg'),
    ('Malawi', 'mw'),
    ('Maldives', 'mv'),
    ('Mali', 'ml'),
    ('Malta', 'mt'),
    ('Marshall Islands', 'mh'),
    ('Mauritania', 'mr'),
    ('Mauritius', 'mu'),
    ('Micronesia', 'fm'),
    ('Monaco', 'mc'),
    ('Montenegro', 'me'),
    ('Mozambique', 'mz'),
    ('Namibia', 'na'),
    ('Nauru', 'nr'),
    ('Nicaragua', 'ni'),
    ('Niger', 'ne'),
    ('Oman', 'om'),
    ('Palau', 'pw'),
    ('Palestine', 'ps'),
    ('Panama', 'pa'),
    ('Papua New Guinea', 'pg'),
    ('Paraguay', 'py'),
    ('Rwanda', 'rw'),
    ('Saint Kitts and Nevis', 'kn'),
    ('Saint Lucia', 'lc'),
    ('Saint Vincent and the Grenadines', 'vc'),
    ('Samoa', 'ws'),
    ('San Marino', 'sm'),
    ('Sao Tome and Principe', 'st'),
    ('Senegal', 'sn'),
    ('Seychelles', 'sc'),
    ('Sierra Leone', 'sl'),
    ('Solomon Islands', 'sb'),
    ('Somalia', 'so'),
    ('South Sudan', 'ss'),
    ('Sudan', 'sd'),
    ('Suriname', 'sr'),
    ('Togo', 'tg'),
    ('Tonga', 'to'),
    ('Trinidad and Tobago', 'tt'),
    ('Tuvalu', 'tv'),
    ('Uganda', 'ug'),
    ('Uruguay', 'uy'),
    ('Vanuatu', 'vu'),
    ('Vatican City', 'va'),
    ('Zambia', 'zm'),
    ('Zimbabwe', 'zw')
) AS v(name, iso)
WHERE lower(trim(f.name)) = lower(v.name)
  AND (f.country_code IS NULL OR trim(f.country_code) = '');
